# Generated by Django 4.2.6 on 2023-12-04 03:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre_usuario', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Atencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solucion', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=20)),
                ('fecha', models.DateField()),
                ('id_ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_ticket.ticket')),
                ('id_trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_ticket.trabajador')),
            ],
        ),
    ]
